### ISSUE TITLE
Vimgifs link in LearningX.md leads to 402

### ISSUE THREAD

**Issue by manaswinidas** [tapasweni-pathak/Getting-Started-With-Contributing-to-Open-Sources#22]
[Vimgifs](https://vimgifs.com/) in LearningX.md leads to a 402 Payment required page

**Comment by vyaspranjal33** [comment]
@manaswinidas  its working fine
![image](https://user-images.githubusercontent.com/11768143/43727367-5fb116ea-99bf-11e8-98f9-e5aa68f0ec62.png)

**Comment by vyaspranjal33** [comment]
@tapasweni-pathak  we can close this issue
